export const SAVE_DATA_FULLFILLED = 'SAVE_DATA_FULLFILLED';
export const SAVE_DATA_LOADING = 'SAVE_DATA_LOADING';
export const SAVE_DATA_REJECTED = 'SAVE_DATA_REJECTED';




export const DELETE_DATA = 'DELETE_DATA';